### PR TITLE
add the trigger and jobs docs for ocp ci

### PR DESCRIPTION
**Pull request by ascerra**

### CODE REVIEW

**Review by Dannyb48 — COMMENTED** [review]
I think the only thing I would like is maybe a job off point in the main readme at the root of the docs?

**Comment by ascerra** [comment]
> I think the only thing I would like is maybe a job off point in the main readme at the root of the docs?

Ya could point and really this root README can just direct you to the gitbook link for this. I'll put both links to the guides and the external URL for gitbook

**Comment by flacatus** [comment]
@ascerra why the gitbook not appear

**Comment by ascerra** [comment]
> @ascerra why the gitbook not appear

The gitbook for this is here: https://rhtap-qe-1.gitbook.io/rhtap-qe

**Pull request merged**
