### PR TITLE
RHTAPBUGS-1327 Add wait for Gitlab repo creation

### PR DESCRIPTION
**Pull request by jkopriva**
+ fix for new version of templates

### CODE REVIEW

**Comment by jkopriva** [comment]
Duplicates are fixed in https://github.com/redhat-appstudio/rhtap-e2e/pull/149/files

This is a fix for templates and and for GitLab repo creation.

**Comment by jduimovich** [comment]
I see the e2e tests use the template variables names which did change.  I had not realized it

The variables were changed so that the template which uses "oneOf" pattern to choose between  git hosts had defaults that worked.  This is a workaround for a bug in RHDH templates which regardless of the "defaults" provided in the oneOf: keys, it uses the "first one" and ignores the rest. 

I created a small example of the issue. 
https://github.com/jduimovich/oneof

The workaround was not to use common properties (glhost, bbhost,ghhost. The template would be easier to write if defaults worked as they could be references one and not with multiple-if-statements

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
