### PR TITLE
RHTAP-3056 GitLab CI tests

### PR DESCRIPTION
**Pull request by jkopriva**

### CODE REVIEW

**Comment by jkopriva** [comment]
image

**Comment by rhopp** [comment]
I've made necessary changes (merge with main branche + removed duplicate function) and run the tests locally. 
Tests started successfully, but the build pipeline failed on 
```
$ bash /work/rhtap/cosign-sign-attest.sh
Step: cosign-sign-attest
Results: /builds/rhtap-qe/itx2qae0l-go/results/cosign-sign-attest
Running cosign-sign-attest:sign
Using IMAGE_REGISTRY_USER and IMAGE_REGISTRY_PASSWORD secrets for registry auth
auth.go:274: logged in via /root/.docker/config.json
Error: signing [rhtap-quay-quay-rhtap-quay.apps.rosa.rhopp-rosa.54x8.p3.openshiftapps.com/rhtap/rhtap-qe:gitlab-c494eeb6677076fb0fa34d1fdddaa91feb775a13@sha[25](https://gitlab.com/rhtap-qe/itx2qae0l-go/-/jobs/8688953475#L25)6:d071873f1b1377ebd1f9cc070c42fc4b032b6822a42053414722207c5ae4ff56]: getting signer: reading key: decrypt: encrypted: decryption failed
main.go:74: error during command execution: signing [rhtap-quay-quay-rhtap-quay.apps.rosa.rhopp-rosa.54x8.p3.openshiftapps.com/rhtap/rhtap-qe:gitlab-c494eeb6677076fb0fa34d1fdddaa91feb775a13@sha256:d071873f1b1377ebd1f9cc070c42fc4b032b6822a42053414722207c5ae4ff56]: getting signer: reading key: decrypt: encrypted: decryption failed
```
I must have have done some mistake in setup. 

Anyway.. I suggest to merge this PR (once through CI) and do any followup fixes in future

**Comment by rhopp** [comment]
1 of 2 runs succeeded -https://console.redhat.com/application-pipeline/workspaces/rhtap-shared-team/applications/rhtap-e2e/pipelineruns/e2e-4.16-wlgps 
The other one failed on rosa provisioning step.
Merging.

**Review by rhopp — APPROVED** [review]

**Pull request merged**
